version: '3.8'

services:
  api:
    image: basic-connect-api-image
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:8080"
    depends_on:
      - db

  db:
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: myRootP4sw0ord
      MYSQL_DATABASE: app_api_db
      MYSQL_USER: user
      MYSQL_PASSWORD: myS3cur3P4ssw0rd
    ports:
      - "3307:3306"